/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */

export * from './detailSchema';
export * from './input';
export * from './loginSchema';
export * from './pagedProductoSchema';
export * from './productoCreateSchema';
export * from './productosApiCreateProductoBody';
export * from './productosApiListProductosLoMasActualizadoParams';
export * from './productosApiListProductosLoMasBaratoParams';
export * from './productosApiListProductosOfertasParams';
export * from './productosApiListProductosParaHombreParams';
export * from './productosApiListProductosParams';
export * from './productosApiListProductosParaMujerParams';
export * from './productosApiUpdateProductoBody';
export * from './productoSchema';
export * from './productoUpdateSchema';
export * from './tokenSchema';