/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */

export interface ProductoCreateSchema {
  nombre: string;
  precio: number;
  para_mujer?: boolean;
  en_oferta?: boolean;
}
