/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */
import type { ProductoCreateSchema } from './productoCreateSchema';

export type ProductosApiCreateProductoBody = {
  imagen?: Blob;
  data: ProductoCreateSchema;
};
