/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */
import type { ProductoUpdateSchema } from './productoUpdateSchema';

export type ProductosApiUpdateProductoBody = {
  imagen?: Blob;
  data: ProductoUpdateSchema;
};
