/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */

export interface ProductoSchema {
  id?: number | null;
  created_at: string;
  updated_at: string;
  /** @maxLength 255 */
  nombre?: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  precio?: string;
  para_mujer?: boolean;
  imagen?: string | null;
  en_oferta?: boolean;
}
