/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */

export interface ProductoUpdateSchema {
  nombre?: string | null;
  precio?: number | null;
  para_mujer?: boolean | null;
  en_oferta?: boolean | null;
}
