/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * BBTITO API
 * OpenAPI spec version: 1.0
 */

export type ProductosApiListProductosLoMasActualizadoParams = {
busqueda?: string | null;
/**
 * @minimum 1
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
